### ISSUE TITLE
New ESDT property 'Can add special role'

### ISSUE THREAD

**Issue by MORPHESDT** [multiversx/mx-assets#1678]
Hello,

How are managed priorities betwenn special roles and ESDT property ?
E.g. Is it possible for someone with mint special role to mint a non mintable token ?

By the way how can we set this Can add special role to no on an non upgradable token such as MPH-f8ea2b ?
Can you perform this action ?

Regards

MorPh_tok

**Comment by Lallement-Kevin** [comment]
As the documentation explain since the epoch 432 we cant use global mint which is related to the "Can Mint" you see in the explorer. So for your answer, YES if the owner of the token use setSpecialRole : ESDTRoleLocalMint to a specific address, theaddress, will be able to mint new tokens with a LocalMintTransaction 

https://docs.multiversx.com/tokens/esdt-tokens/#upgrading-changing-properties
https://docs.multiversx.com/tokens/esdt-tokens/#setting-and-unsetting-special-roles
https://docs.multiversx.com/tokens/esdt-tokens/#minting

**Comment by Lallement-Kevin** [comment]
Made a test for you on devnet : 
test token : 
https://devnet2-explorer.multiversx.com/tokens/MINT-79edf5

initial issuance : 
https://devnet2-explorer.multiversx.com/transactions/0500590c1c49e3aabe7cc3cdf8637c9c715f0a3016aa6fc487351315cc125640

setting role to another adresse :
https://devnet2-explorer.multiversx.com/transactions/6d2b2211897727d33eac1de7414a7d018337696eae6843a1ee77b896b44ebc19

new mint from address  : 
https://devnet2-explorer.multiversx.com/transactions/79127d5c38c477407c2e050e84e34f0e63b3d00210b7000f9a9a006cdf8652d9

**Comment by MORPHESDT** [comment]
Thanks a lot for this clear answer !
